import type { AudiogramSettings } from './types';

export interface AudiogramVisualPreset {
  id: string;
  name: string;
  description: string;
  settings: Partial<AudiogramSettings>;
}

export const AUDIOGRAM_VISUAL_PRESETS: AudiogramVisualPreset[] = [
  {
    id: 'signature',
    name: 'Ampersand Signature',
    description: 'Warm cinematic depth with a luminous centered waveform.',
    settings: {
      background_mode: 'gradient',
      background_color: '#101718',
      accent_color: '#e1b977',
      waveform_color: '#f3cc8a',
      text_color: '#f8f4ec',
      background_dim: 0.08,
      background_blur: 0,
      background_vignette: 0.45,
      waveform_style: 'mirrored',
      waveform_scale: 'sqrt',
      waveform_position: 'center',
      waveform_width_percent: 84,
      waveform_height_percent: 30,
      waveform_glow: 0.58,
      waveform_frame: 'glass',
      font_family: 'sans',
      text_align: 'center',
      text_position: 'top',
      text_panel: 'shadow',
    },
  },
  {
    id: 'editorial',
    name: 'Clean Editorial',
    description: 'Quiet magazine styling for interviews, vows, and narration.',
    settings: {
      background_mode: 'color',
      background_color: '#f1ede4',
      accent_color: '#b56f45',
      waveform_color: '#1c292b',
      text_color: '#182224',
      background_dim: 0,
      background_blur: 0,
      background_vignette: 0,
      waveform_style: 'line',
      waveform_scale: 'linear',
      waveform_position: 'bottom',
      waveform_width_percent: 88,
      waveform_height_percent: 18,
      waveform_glow: 0,
      waveform_frame: 'none',
      font_family: 'serif',
      text_align: 'left',
      text_position: 'top',
      text_panel: 'none',
    },
  },
  {
    id: 'neon',
    name: 'Neon Pulse',
    description: 'A reactive spectrum with deep color and vivid glow.',
    settings: {
      background_mode: 'radial',
      background_color: '#080b18',
      accent_color: '#ff3ea5',
      waveform_color: '#4cf5d2',
      text_color: '#f7fbff',
      background_dim: 0.06,
      background_blur: 0,
      background_vignette: 0.62,
      waveform_style: 'spectrum',
      waveform_scale: 'sqrt',
      waveform_position: 'center',
      waveform_width_percent: 90,
      waveform_height_percent: 40,
      waveform_glow: 0.9,
      waveform_frame: 'outline',
      font_family: 'mono',
      text_align: 'center',
      text_position: 'top',
      text_panel: 'glass',
    },
  },
  {
    id: 'wedding',
    name: 'Wedding Glow',
    description: 'Soft champagne tones built for ceremonies and speeches.',
    settings: {
      background_mode: 'radial',
      background_color: '#281b23',
      accent_color: '#d8b77c',
      waveform_color: '#f7dfb0',
      text_color: '#fff8ed',
      background_dim: 0.1,
      background_blur: 0,
      background_vignette: 0.52,
      waveform_style: 'mirrored',
      waveform_scale: 'cbrt',
      waveform_position: 'bottom',
      waveform_width_percent: 80,
      waveform_height_percent: 25,
      waveform_glow: 0.68,
      waveform_frame: 'glass',
      font_family: 'serif',
      text_align: 'center',
      text_position: 'top',
      text_panel: 'shadow',
    },
  },
  {
    id: 'social',
    name: 'Bold Social',
    description: 'High-energy color, chunky bars, and strong mobile contrast.',
    settings: {
      background_mode: 'gradient',
      background_color: '#d83d55',
      accent_color: '#ffd166',
      waveform_color: '#ffffff',
      text_color: '#ffffff',
      background_dim: 0.02,
      background_blur: 0,
      background_vignette: 0.25,
      waveform_style: 'bars',
      waveform_scale: 'cbrt',
      waveform_position: 'bottom',
      waveform_width_percent: 92,
      waveform_height_percent: 24,
      waveform_glow: 0.25,
      waveform_frame: 'accent',
      font_family: 'sans',
      text_align: 'left',
      text_position: 'top',
      text_panel: 'accent',
    },
  },
  {
    id: 'broadcast',
    name: 'Midnight Broadcast',
    description: 'A crisp frequency display with a restrained studio finish.',
    settings: {
      background_mode: 'gradient',
      background_color: '#071b2a',
      accent_color: '#33b7c5',
      waveform_color: '#e9f9ff',
      text_color: '#edf8fb',
      background_dim: 0.12,
      background_blur: 0,
      background_vignette: 0.48,
      waveform_style: 'spectrum_dots',
      waveform_scale: 'log',
      waveform_position: 'bottom',
      waveform_width_percent: 90,
      waveform_height_percent: 28,
      waveform_glow: 0.62,
      waveform_frame: 'glass',
      font_family: 'sans',
      text_align: 'left',
      text_position: 'top',
      text_panel: 'glass',
    },
  },
];

export function applyAudiogramPreset(
  current: AudiogramSettings,
  preset: AudiogramVisualPreset,
): AudiogramSettings {
  return { ...current, ...preset.settings, spec_version: '1.1' };
}

export function matchesAudiogramPreset(
  settings: AudiogramSettings,
  preset: AudiogramVisualPreset,
): boolean {
  return Object.entries(preset.settings).every(
    ([key, value]) => settings[key as keyof AudiogramSettings] === value,
  );
}
